### ISSUE TITLE
Snap to grid/snap to ground

### ISSUE THREAD

**Issue by kiwidoggie** [Powback/MapEditor#160]
It would be nice to have a snap to grid functionality, as well as snap to ground functionality (to prevent floating objects)

**Comment by FoolHen** [comment]
Snap to grid is a thing, hold control while interacting with the gizmo. Snap to ground has to be reimplemented, it was a thing before.

**Comment by kiwidoggie** [comment]
<3

**Comment by Powback** [comment]
Hold shift + center of gizmo to raycast place in latest build. ctrl to snap to grid
