### ISSUE TITLE
Sometimes loading a save loads the incorrect map.

### ISSUE THREAD

**Issue by kiwidoggie** [Powback/MapEditor#176]
Found a few days ago with working with Uncharted. I don't know exactly what causes this. But here's one repro, 

You can go on any map MP_001, create a map, save it. Reload the server (MP_001), and load the file, it switches to another map. 

Or, Restart the server on XP1_001, load the map from MP_001, get switched to XP2_xxx (or some random map, that the saved map was not created on)

**Comment by FoolHen** [comment]
Due to https://github.com/EmulatorNexus/VeniceUnleashed/issues/726

**Comment by FoolHen** [comment]
Fixed in c555d0511c72235c14ecf32cb18ef060aa5bdc64
