### ISSUE TITLE
Server crash on removing any drivable vehicle after manually spawned.

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#197]
Map: Seine Crossing
Mode: Conquest Large

Crash ID: f7fff68d-839b-44f6-8ef6-989cb0aa0fcc
Build Number: 17182
Release Branch: prod

**Comment by Powback** [comment]
https://github.com/EmulatorNexus/VeniceUnleashed/issues/535

**Comment by Powback** [comment]
Solved in latest
