### ISSUE TITLE
Right-clicking after pressing Alt and Left-click while in freecam causes the viewport to invert itself.

### ISSUE THREAD

**Issue by TheProgramableTurtle** [Powback/MapEditor#204]
The viewport inverts itself as below when the right mouse button is clicked after the left mouse button and the Alt key have been pressed in combination.
![image](https://user-images.githubusercontent.com/44685118/97021418-b9914280-154a-11eb-8ffd-d2f67e2b2fa1.png)
Neither F3 nor F5 resets this and the only way to do so is to reconnect to the server.

**Comment by FoolHen** [comment]
It's fixed in the last commit

**Comment by TheProgramableTurtle** [comment]
Looks like I was too slow, fixed in #7180a55

**Comment by TheProgramableTurtle** [comment]
And looks like I was also too slow to close lol
