### ISSUE TITLE
Scroll Wheel doesn't change movement speed

### ISSUE THREAD

**Issue by JoseFigueiras** [Powback/MapEditor#212]

**Comment by FoolHen** [comment]
It does, it's just less sensible. I'll increase it again, as it's too slow.

**Comment by Powback** [comment]
I can toggle the mousewheel scroll click on my mouse, so I usually just let it spin while moving around, but I can see why it would be annoying on mouses without that feature. 

We should probably adjust it from steps to some kind of curve.

**Comment by FoolHen** [comment]
Its already a curve, the slower it goes the slower the steps are. The issue is that I made the sensitivity too low.

**Comment by FoolHen** [comment]
My bad, it wasn't a curve. Now it is and its sesitivity has been increased in 3d61197
