### ISSUE TITLE
Keyboard shortcuts to move assets way faster.

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#234]
Ctrl + Left click + drag = move on X axis
Ctrl + Right click + drag = move on Y axis
Ctrl + Left click + Right click + drag = move on Z axis
These options also used for Rotation and Scale Transform.

**Comment by 3ti65** [comment]
The CTRL modifier is reserved for multiselection and gridsnap. Won't do anything for now, maybe later down the line.
