### ISSUE TITLE
Export code order

### ISSUE THREAD

**Issue by Dirteebreaks** [Powback/MapEditor#238]
Feature request

I would love to be able to read the export code nore easily so I can back track where or what went wrong when a map does not load/server crashes on boot.

If we could get the export code to export in the order in which we created/edited things, it would be awesome.

Also if a new line was made after every ending bracket  },  
It would make reading so much easier.

Maps load just fine with said new lines in as i reformat my export code to this anyway. It makes it so much easier to read.

**Comment by FoolHen** [comment]
Adding spaces and line breaks increase the file size, which we dont want. You can use an online json beautifier right after copying the save file to make it more readable.

**Comment by 3ti65** [comment]
wont fix, not feasible. we wont design the persistence layer based on back-traceability and readability.
