### ISSUE TITLE
Scroller placed inside scrollable element

### ISSUE THREAD

**Issue by Powback** [Powback/MapEditor#262]
PerfectScrollbar scrollers are placed inside the element they're scrolling in some components.

The scene hierarchy works fine, the console and inspector does not.

**Comment by FoolHen** [comment]
@kaloczikvn is this something you fixed?

**Comment by kaloczikvn** [comment]
> @kaloczikvn is this something you fixed?

Nope, but it is fixed, right?

**Comment by FoolHen** [comment]
I think so yeah, closing
