### ISSUE TITLE
Random assets makes client crash on round restart.

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#264]
This is completly random and changes between levels, maybe in XP3_Shield a prop called _rock_01wall_ works fine and then in XP3_Bandar the same asset makes the client crash.

This is completly arbitrary between levels and assets.

**Comment by FlashHit** [comment]
Check this:
https://github.com/FlashHit/MapLoader/tree/map-reload-fix

**Comment by FlashHit** [comment]
Oh and it's not 'random', or at least in your example. In XP3_Shield the _rock_01wall_ works fine because this object exists on that map already, while in XP3_Bandar you need to bundle another map to use that object.
So this is probably more `Assets from other map bundles` then `Random assets`

**Comment by keku645** [comment]
I guess this can now be closed until further advise? 
It has been fixed on the latest maploader update, only assets that contain **VegetationTreeEntityData** crash now.
