### ISSUE TITLE
New asset is occasionally invisible until client reloads

### ISSUE THREAD

**Issue by SassythSasqutch** [Powback/MapEditor#265]
[Can be seen in this video](https://youtu.be/rLPJNzba8CI).

When placing, pasting, etc. - seemingly any time a new BP is being spawned. The UI wireframe for the asset is visible, and so the asset can be moved around, modified, and copied. The asset in question will only become visible when the client leaves and rejoins.

- It seems to happen with varying frequency. Sometimes it happens 75% of the time when spawning a new asset, sometimes 5% of the time. 

- It might become more frequent over time (i.e. when you first start the server and start doing things, it's rare, but after an hour or two of work, it's common).

https://discord.com/channels/125257766649593856/773652432835313664/814601695605555202
Apologies for not making this earlier I completely forgot.

**Comment by FoolHen** [comment]
@SassythSasqutch  Video says 10th of january commit, is this happening with latest? I pushed a fix for this the other day

**Comment by SassythSasqutch** [comment]
Apologies, I had no idea a fix was pushed. I don't have a chance to test it for the next week but if you fixed it it's probably fixed - I'll close this.
