### ISSUE TITLE
Connection to the server timed out when placing prefabs that contain logic

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#266]
When placing a prefab that contains animations props wont spawn and also after X seconds you get kicked out with a "The connection to the server timed out" error.

Appart from that you're forced to close the server through task manager because it gets stuck.

https://user-images.githubusercontent.com/36018654/114178389-f5279980-993d-11eb-8559-26b9da8be4b8.mp4

**Comment by keku645** [comment]
Updating this, its not with assets that contains animations, it is random on prefabs. Doesnt have to contain an animation.

**Comment by FoolHen** [comment]
Its most likely due to logic, EventConnections and PropertyConnections

**Comment by FoolHen** [comment]
Possibly fixed in 9ac6033ad326257d4ebc354a72ac3370fcd09874
