### ISSUE TITLE
Objects with `VegetationTreeEntityData` crash on map restart

### ISSUE THREAD

**Issue by FlashHit** [Powback/MapEditor#267]
https://github.com/EmulatorNexus/Venice-EBX/blob/master/Objects/Vegetation/TreeBeech_M_02_Cluster/TreeBeech_M_02_Cluster.txt
https://github.com/EmulatorNexus/Venice-EBX/blob/master/Objects/Vegetation/TreeAspen_L_01/TreeAspen_L_01.txt

Crash on maprestart.
I assume it has to do with the `VegetationTreeEntityData` because all other objects don't make the server crash on restart for me. 
Tested with `XP5_003 CQL`.
(in addition to #264)

**Comment by FoolHen** [comment]
Closing as it's a maploader issue
