### ISSUE TITLE
Invisible assets only on mapeditor mode

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#270]
There are some assets that are invisible on editor mode, which are visible when you load the map without it.
On Kiasar Railroad, Conquest Large mode.
SupplyShip asset.
Bundles added: xp3_shield, xp3_alborz, XP1_004.
![image](https://user-images.githubusercontent.com/36018654/115502718-a7802a80-a275-11eb-8a87-369c537f08fd.png)

**Comment by FoolHen** [comment]
Was the same issue as https://github.com/BF3RM/MapEditor/issues/273
