### ISSUE TITLE
mod.db file wont decrease it's size when removing old saves

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#272]
It's size will only increase, never decrease.

![image](https://user-images.githubusercontent.com/36018654/116248190-eb8a9800-a76b-11eb-87c8-83b978c11ede.png)

[https://mega.nz/file/FddzkYjQ#fFkWf_f6kGy-eGcRgCE4MXWEMeSHRBgAjNF0BR0sCS0](url)

**Comment by FoolHen** [comment]
Fixed in 9c8d218
