### ISSUE TITLE
Removed vanilla assets are still "there" in mapeditor mode

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#273]
Removed vanilla assets are still visibly there when loading the file through mapeditor but they're not there to be selected neither clicking the objects themselves or through the asset list.
After that, loading the mapfile with maploader the assets are removed.

Asset name: Tree_Pine_Cluster_01
Map: XP3_Alborz
Mode: ConquestLarge0
No other bundles loaded

![1](https://user-images.githubusercontent.com/36018654/117099678-0ebbd580-ad72-11eb-94c6-036fbe4c24b6.PNG)
![Vu Screenshot 2021 05 05 - 07 09 58 48](https://user-images.githubusercontent.com/36018654/117099681-0fed0280-ad72-11eb-89c1-490750a35384.png)

**Comment by FoolHen** [comment]
Fixed in 7176702
