### ISSUE TITLE
Your local content does not match the content on the server error when reloading the map.

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#279]
This happens when you have a save with modified/removed vanilla assets, when the map is reloaded, then you leave the server and join back in this error prompts.

![image](https://user-images.githubusercontent.com/36018654/118536605-3769a500-b74c-11eb-99a4-020264b45c3d.png)

**Comment by FoolHen** [comment]
https://github.com/BF3RM/MapLoader/issues/5
