### ISSUE TITLE
Random assets can't be selected through the bounding box.

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#286]
This happens in any map, any mode with any custom map or vanilla assets.

You're forced to select these assets through the asset list, maybe next time you reload the server, the assets that didn't have a bounding box to be selected, now do have one and others that had bounding box wont have this time.

In this case:

Map: xp5_003 / ConquestLarge0

Bundles added:  xp3_alborz, xp3_Shield, xp1_004, coop_010

![Vu Screenshot 2021 07 05 - 18 11 42 51](https://user-images.githubusercontent.com/36018654/124498634-f5a8c280-ddbc-11eb-9a98-29e2a441dbc9.png)

![Vu Screenshot 2021 07 05 - 18 19 12 90](https://user-images.githubusercontent.com/36018654/124498971-867f9e00-ddbd-11eb-87f8-cb03f5259d50.png)

**Comment by FoolHen** [comment]
Should be fixed in 39e67e0
