### ISSUE TITLE
[bug] Letters are being removed when you undo.

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#293]
https://user-images.githubusercontent.com/36018654/126872474-3c016e3b-4daa-461a-9159-1aaf15881598.mp4

Every time you do ctrl + z, appart from undo, it also removes letter by letter on the searcher bar.

**Comment by FlashHit** [comment]
Not really a bug but I guess we couldn’t unselect the textfield.

**Comment by FoolHen** [comment]
Caused by https://github.com/BF3RM/MapEditor/issues/347
