### ISSUE TITLE
[BUG] Latest maped version wont spawn VegetationTreeEntity assets?

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#295]
Latest maped version from #development branch.

https://user-images.githubusercontent.com/36018654/126873811-0b985217-d7d4-4514-b1c8-65e950934cb1.mp4

Latest version from #test branch

https://user-images.githubusercontent.com/36018654/126873816-683b129b-2fc9-4935-b965-f6bb4de40628.mp4

No other mods nor sided bundles, pure vanilla.

**Comment by FoolHen** [comment]
Fixed in e43d4a78a126f2fc3d6710147bba976bf4a4b9d8
