### ISSUE TITLE
[BUG] Connection to the server timed out when loading a save with a lot of assets.

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#297]
When loading a save that contains a lot of assets, you get a connection to the server timed out error.
Seems to be the same error we used to have a couple of months ago, waiting for all the assets to spawn doesnt seem to fix it.

[https://www.youtube.com/watch?v=V1Q4DSEYXFA](url)

**Comment by kapraran** [comment]
https://github.com/BF3RM/MapEditor/blob/development/ext/Server/ServerTransactionManager.lua#L3

change this `true` in this line to `false`

**Comment by keku645** [comment]
Didn't work, apparently is a completely different issue.

**Comment by keku645** [comment]
Closing because its a completely different thing.
