### ISSUE TITLE
[BUG] Latest maped version wont load any save.

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#298]
All saves are broken, even making a new save from a blank map it wont load.

XP3_Desert TeamDeathMatch0 as an example.

[https://www.youtube.com/watch?v=oacL5BD_buU](url)

This is what server prints when loading this save.

![image](https://user-images.githubusercontent.com/36018654/126917262-b5eb377a-9870-4c51-b115-09d4861fc43c.png)

**Comment by FoolHen** [comment]
Fixed in 0ff92ac
