### ISSUE TITLE
[BUG] The connection to the server time out when loading a save with a huge amount of assets. (old bug)

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#299]
This is an old bug, when loading a save that contains a huge amount of assets the connection to the server will time out.

It should be fixable like in the old versions of maped, first letting the player join the server then load the chunks of the map, but in this case it doesnt let the player to join and kicks you out of the server first, then loads the chunks of the map.

Even waiting for the server to load all assets and joining later this wont fix the issue because the amount of assets is so large client silent crashes.

Happens in all saves I tested, this is an example with the BR save.

[https://www.youtube.com/watch?v=9ZPQv_zkOKw](url)

**Comment by Powback** [comment]
Seems to be caused by console spam. Try setting these two lines to false:
https://github.com/BF3RM/MapEditor/blob/development/ext/Server/ServerTransactionManager.lua#L3
https://github.com/BF3RM/MapEditor/blob/development/ext/Client/ClientTransactionManager.lua#L3

Fool probably enabled the logger for debug purposes.

**Comment by keku645** [comment]
Yep, that seemed to have fixed it.

**Comment by FoolHen** [comment]
Ah yeah, test branch is the one you want to use as it doesn't have debug stuff enabled. I'll update test branch soon with the latest changes.

**Comment by keku645** [comment]
Reopening again because still happens.

**Comment by keku645** [comment]
Still happens but, now you may also get a silent crash. Everything is turned OFF as you mentioned.

[https://www.youtube.com/watch?v=4h1r2iFwWS8](url)

**Comment by keku645** [comment]
This bug still happens but is random, everything is turned off as you mentioned. 

[https://www.youtube.com/watch?v=4h1r2iFwWS8](url)

**Comment by keku645** [comment]
Opening again because still happens, not as usual but still happens.
