### ISSUE TITLE
[BUG] Maped freezes when selecting the first asset when loading a save (UI)

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#303]
The more assets your map has the more time the map freezes, the gizmo takes A LOT of time to appear once the first asset is selected, and afterwards when you do the first action like adding a new asset, remove or duplicate it also freezes for a long time.

Development branch.

Bundles used: xp3_alborz, xp3_Shield, xp1_004, coop_010.
Map: XP5_003

Video example: [https://www.youtube.com/watch?v=yZYGLf4PrA0](url)

**Comment by FoolHen** [comment]
This is because theres unfinished features in development branch, use test branch instead.
