### ISSUE TITLE
[BUG] Mapeditor freezes for X period of time after all assets are loaded

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#305]
The greater the amount of assets the longer you have to wait, currently on Kiasar BR map with 9k assets i have to wait around 15min to start working on the map.

Things to notice:

Even tho all assets are loaded you can see on the custom folder the number of assets is stuck way below the actual number of assets are on the map, after you wait X time, it shows the correct number of assets and then you can use the editor.

While stuck:
![image](https://user-images.githubusercontent.com/36018654/130454778-fb578755-7632-4927-b950-fabbef646eec.png)

Once you can use the editor: 
![image](https://user-images.githubusercontent.com/36018654/130455183-41bcd2ca-fcdf-4c7d-b6fa-f3b39dc713c7.png)

Map and mode: XP5_003 ConquestLarge0

Bundles: Coop_010, XP1_004, XP3_Shield, XP3_Alborz

Maped branch: Test

**Comment by keku645** [comment]
Increasing ``queue_max_commands`` doesn't fix the issue.

**Comment by FoolHen** [comment]
Fixed in aa7d66ed8563bed41723355a2dc10fc094be9661
