### ISSUE TITLE
[BUG] mp_subway does not load any save on any mode

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#307]
**mp_subway** doesn't load any save from any mode, you always get a **The connection to the server timed out** error.

**Comment by kapraran** [comment]
![image](https://user-images.githubusercontent.com/1511946/134084183-fde1d46d-5d1a-4e90-ab37-bea39f020b34.png)

This may help. This is the console while trying to load a save with only one random custom item. (the client silent crashes)
Also the loading even though it starts normally, it freezes at some point which may mean, also based on the message, that it got struct respawning that same item over and over again.

**Comment by keku645** [comment]
Latest commit where maped worked: https://github.com/BF3RM/MapEditor/tree/b950f48b9e3fd3df881c66a3a35886ed507d9e34

**Comment by keku645** [comment]
Closing, apparently got fixed on latest.
