### ISSUE TITLE
[BUG] Half broken gizmo/bounding box when spawning a new asset. [Dev Branch]

### ISSUE THREAD

**Issue by keku645** [Powback/MapEditor#312]
When spawning a new asset there's no gizmo either you can't select it clicking on it, you're forced to click random assets from the vanilla list and back to your custom placed asset until the gizmo appears back.

Also seems that when you remove an asset (hand placed) it is still there on the list as a name.

https://youtu.be/MzoXDcC8TOk

https://github.com/BF3RM/MapEditor/tree/0b7b73a12d571021240db71f3921b617ee6ba8f6

**Comment by keku645** [comment]
Updating with more bugs.
https://www.youtube.com/watch?v=48yz26Ko83w

**Comment by FoolHen** [comment]
Development branch is for that, development, stuff usually breaks when working on new features and fixes. Im aware of the issues, they are due to the new instancing system.

**Comment by FoolHen** [comment]
Fixed in cfac0a3bcc7fc9fb0ba30944bc8e7a0576fd23e6
