### ISSUE TITLE
Unexpected behaviour when scaling multiple assets

### ISSUE THREAD

**Issue by SassythSasqutch** [Powback/MapEditor#324]
- Position transform changes 
- Some objects are scaled more than expected

Both visible here:

https://cdn.discordapp.com/attachments/486811627035951105/938193079867936887/fucking_scaling.mp4

**Comment by FoolHen** [comment]
Might have been fixed in 23e45c8adb426be9a618283fa32a31d8faf4e072 (if so, its related to https://github.com/BF3RM/MapEditor/issues/342), please test again and let me know how to easily reproduce it.
