### ISSUE TITLE
[Bug] multiselection when filtering is broken 

### ISSUE THREAD

**Issue by 3ti65** [Powback/MapEditor#332]
When using multiselection (SHIFT + MOUSE1) on filtered items, it will select hidden items in at least the Scene Instances view.

https://user-images.githubusercontent.com/12377272/154131077-6555c729-6457-4fa5-9451-a0342e6d7f3c.mp4

**Comment by FoolHen** [comment]
Fixed in 533e0cfde84c8978c62703486a967de601cca676
