### ISSUE TITLE
Redesign the whole UI to make it consistent and easier to navigate

### ISSUE THREAD

**Issue by FoolHen** [Powback/MapEditor#356]

**Comment by FoolHen** [comment]
Add tooltip messages to these icons in toolbar:
![Image](https://user-images.githubusercontent.com/7466799/171992721-9583231c-01cf-435c-acb8-c3db4894f69f.png)

Can you change the tooltip text to `Visible`? More concise.
![Image](https://user-images.githubusercontent.com/7466799/171992628-27f2977c-e63a-4959-bfc9-4e3cb4dfffc1.png)

**Comment by FoolHen** [comment]
Also, reduce spacing here so more logs are visible


![Image](https://user-images.githubusercontent.com/7466799/171992684-1d36fd73-85a8-4bac-867d-ab0c11a8a85b.png)

The gap above the first entry is also too big

**Comment by FoolHen** [comment]
Rename to Logs (or Logcat), as console implies that you can enter commands

![Image](https://user-images.githubusercontent.com/7466799/171992917-b1a69115-f28e-452d-8961-ec36cacc2b5e.png)

**Comment by kaloczikvn** [comment]
Done
