### ISSUE TITLE
Preview-spawning

### ISSUE THREAD

**Issue by Powback** [Powback/MapEditor#46]
Objects should be spawnable as previews, clientside only.

**Comment by Powback** [comment]
Make the object really small and draw it right in front of the camera? Maybe add some rotation?

**Comment by 3ti65** [comment]
The best way for previewing stuff might still be extracting the meshes and then creating 1-4 images (all sides) for each object.

**Comment by Powback** [comment]
Noooooo, that's gonna bolat the shit out of it

**Comment by 3ti65** [comment]
Not if it gets pulled on demand from an online database

**Comment by Raikem** [comment]
It shouldn't be too hard, we can make it so it only selects custom objects

**Comment by Powback** [comment]
Clientside-previews implemented using drag & drop.
