### ISSUE TITLE
Add grouping functionality for spawned objects

### ISSUE THREAD

**Issue by 3ti65** [Powback/MapEditor#6]
Add the option to create folder like grouping for spawned objects.
Example:

+ village1
   + building1
         house_villa
         pool
         shed
         bush
+ village 2
     ....

where 'village1, building1 & village2 are user created folders / groups, that persist.
The goal is to be able to have a good structure to the spawned objects.
Also one should be able to copy and delete whole folders.

**Comment by Powback** [comment]
For the UI part, I'm gonna use http://johnny.github.io/jquery-sortable/, which seems like the best solution. 

The default three.js grouping works fine, but I'm sure I can come up with a better solution.

**Comment by 3ti65** [comment]
Looks good

**Comment by Powback** [comment]
Shit's implemented. And by god, it's amazing.
