### ISSUE TITLE
Add "don't show this dialog again" checkbox on the deletion dialog

### ISSUE THREAD

**Issue by 3ti65** [Powback/MapEditor#60]
As the title reads. it becomes very annoying after a couple of times. It's not that hard to figure out that delete actually deletes an object. Also we still have the undo / redo if you delete something by accident.

**Comment by Powback** [comment]
Will remove the deletion dialog if it's for a single item.

**Comment by 3ti65** [comment]
Then its still going to be annoying. Remove it alltogether i guess. Ctrl-z is god

**Comment by Powback** [comment]
Alright, deletion warnings will be removed.

**Comment by Powback** [comment]
Deletion dialog removed, deletion command made into a bulkcommand.
